steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/docker:$COMMIT_SHA'
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/docker:$COMMIT_SHA'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/docker:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
    entrypoint: gcloud
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/docker:$COMMIT_SHA'

